[package]
name = "worker-rpc-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits"] } # extra traits provides Debug etc
#syn = { version = "1.0", features = ["parsing", "proc-macro"] }
quote = { version = "1.0" }
proc-macro2 = "1.0"
