// Generated by web-rpc. Do not edit.

export type Colour = "Red" | "Green";
export type Point = { x: number; y: number; };
export type Shape = { tag: "Empty" } | { tag: "Circle"; value: number } | { tag: "Segment"; value: [number, number] } | { tag: "Label"; text: string; at: Point };
export type Everything = { flag: boolean; small: number; signed_small: number; short: number; signed_short: number; wide: bigint; signed: bigint; huge: bigint; signed_huge: bigint; ratio: number; letter: string; name: string; blob: Uint8Array; points: (Point)[]; pair: [number, string]; lookup: Map<string, number>; maybe: (Colour | undefined); outcome: { tag: "Ok"; value: Point } | { tag: "Err"; value: string }; nothing: undefined; };

/** A request in flight. Awaiting it yields the response; `abort` cancels it. */
export type Request<T> = Promise<T> & { abort(): void };

/** A stream in flight. `close` stops the producer; `done` settles when it ends. */
export interface Subscription {
  close(): void;
  done: Promise<void>;
}

/** A transport this endpoint can be handed. It is never created or closed here. */
export type Endpoint = Worker | MessagePort | DedicatedWorkerGlobalScope;

/** The methods this endpoint must implement. Every one is required. */
export interface Display {
  ping(): number | Promise<number>;
  colours(count: number): Iterable<Colour> | AsyncIterable<Colour>;
  delete_(point: Point): Point | Promise<Point>;
}

export type CalculatorClientOptions = {
  endpoint: Endpoint;
  handlers: Display;
};

export declare class CalculatorClient {
  constructor(options: CalculatorClientOptions);
  add(left: number, right: number): Request<number>;
  note(message: string): void;
  describe(shape: Shape): Request<Everything>;
  echo(value: string): Request<string>;
  upload(buffer: ArrayBuffer): Request<number>;
  lookup(key: number): Request<(string | undefined)>;
  counters(count: number, callback: (item: number) => void | Promise<void>): Subscription;
  tail(delete_: number, extra?: number): Request<number>;
  nothing(): void;
  borrowed(text: string, data: Uint8Array): Request<number>;
  /** Detach listeners, reject pending requests and close open streams. */
  close(): void;
}
