// Generated by web-rpc. Do not edit.

/** A request in flight. Awaiting it yields the response; `abort` cancels it. */
export type Request<T> = Promise<T> & { abort(): void };

/** A stream in flight. `close` stops the producer; `done` settles when it ends. */
export interface Subscription {
  close(): void;
  done: Promise<void>;
}

/** A transport this endpoint can be handed. It is never created or closed here. */
export type Endpoint = Worker | MessagePort | DedicatedWorkerGlobalScope;

export type ClockClientOptions = {
  endpoint: Endpoint;
};

export declare class ClockClient {
  constructor(options: ClockClientOptions);
  now(): Request<bigint>;
  /** Detach listeners, reject pending requests and close open streams. */
  close(): void;
}
