// Generated by web-rpc. Do not edit.

export type Stats = { label: string; count: number; };
export type Fault = { tag: "NotFound" } | { tag: "Bad"; value: string };

/** A request in flight. Awaiting it yields the response; `abort` cancels it. */
export type Request<T> = Promise<T> & { abort(): void };

/** A stream in flight. `close` stops the producer; `done` settles when it ends. */
export interface Subscription {
  close(): void;
  done: Promise<void>;
}

/** A transport this endpoint can be handed. It is never created or closed here. */
export type Endpoint = Worker | MessagePort | DedicatedWorkerGlobalScope;

/** The methods this endpoint must implement. Every one is required. */
export interface Sample {
  add(left: number, right: number): number | Promise<number>;
  wide(value: bigint): bigint | Promise<bigint>;
  blob(data: Uint8Array): number | Promise<number>;
  stats(label: string, count: number): Stats | Promise<Stats>;
  echo(value: string): string | Promise<string>;
  take(buffer: ArrayBuffer): number | Promise<number>;
  give(size: number): ArrayBuffer | Promise<ArrayBuffer>;
  maybe(present: boolean): (string | undefined) | Promise<(string | undefined)>;
  fallible(succeed: boolean): number | Promise<number>;
  fallibleText(succeed: boolean): number | Promise<number>;
  note(message: string): void;
  notes(): number | Promise<number>;
  counters(count: number): Iterable<number> | AsyncIterable<number>;
  slow(millis: number): number | Promise<number>;
  borrowed(text: string, data: Uint8Array): string | Promise<string>;
}

export type SampleServiceOptions = {
  endpoint: Endpoint;
  handlers: Sample;
};

export declare class SampleService {
  constructor(options: SampleServiceOptions);
  /** Detach listeners, reject pending requests and close open streams. */
  close(): void;
}
