// Generated by web-rpc. Do not edit.

export type Stats = { label: string; count: number; };
export type Fault = { tag: "NotFound" } | { tag: "Bad"; value: string };

/** A request in flight. Awaiting it yields the response; `abort` cancels it. */
export type Request<T> = Promise<T> & { abort(): void };

/** A stream in flight. `close` stops the producer; `done` settles when it ends. */
export interface Subscription {
  close(): void;
  done: Promise<void>;
}

/** A transport this endpoint can be handed. It is never created or closed here. */
export type Endpoint = Worker | MessagePort | DedicatedWorkerGlobalScope;

export type SampleClientOptions = {
  endpoint: Endpoint;
};

export declare class SampleClient {
  constructor(options: SampleClientOptions);
  add(left: number, right: number): Request<number>;
  wide(value: bigint): Request<bigint>;
  blob(data: Uint8Array): Request<number>;
  stats(label: string, count: number): Request<Stats>;
  echo(value: string): Request<string>;
  take(buffer: ArrayBuffer): Request<number>;
  give(size: number): Request<ArrayBuffer>;
  maybe(present: boolean): Request<(string | undefined)>;
  fallible(succeed: boolean): Request<number>;
  fallibleText(succeed: boolean): Request<number>;
  note(message: string): void;
  notes(): Request<number>;
  counters(count: number, callback: (item: number) => void | Promise<void>): Subscription;
  slow(millis: number): Request<number>;
  borrowed(text: string, data: Uint8Array): Request<string>;
  /** Detach listeners, reject pending requests and close open streams. */
  close(): void;
}
